services:
  backend:
    build:
      context: ./backend
    container_name: farpost-backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ""
    container_name: farpost-frontend
    depends_on:
      - backend
    ports:
      - "5173:80"
